/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp_etapa2_nickbruno;

import javax.swing.JOptionPane;

/**
 *
 * @author Yudi
 */
public class Menu extends javax.swing.JFrame {

    /*private String l = "TrabalhoCadastro.txt";*/
    private Pessoa p[] = new Pessoa[100];
    private int i = 0;
    private int x[] = new int[100];
    private int aux2;
    private int exAux = -1;

    /*private String aux;*/

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        tab = new javax.swing.JTabbedPane();
        cadP = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        nomeCamp = new javax.swing.JTextField();
        idadeLabel = new javax.swing.JLabel();
        idadeCamp = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfCamp = new javax.swing.JTextField();
        sLabel = new javax.swing.JLabel();
        sMasc = new javax.swing.JRadioButton();
        sFem = new javax.swing.JRadioButton();
        cLabel = new javax.swing.JLabel();
        cSim = new javax.swing.JRadioButton();
        cNao = new javax.swing.JRadioButton();
        rLabel = new javax.swing.JLabel();
        rSim = new javax.swing.JRadioButton();
        rNao = new javax.swing.JRadioButton();
        tLabel = new javax.swing.JLabel();
        tipoCampo = new javax.swing.JTextField();
        cadB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cpfPanel2 = new javax.swing.JLabel();
        pesqCamp = new javax.swing.JTextField();
        pesqB = new javax.swing.JButton();
        status = new javax.swing.JPanel();
        statusL = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cpfLabel2 = new javax.swing.JLabel();
        pesqCamp2 = new javax.swing.JTextField();
        pesqB2 = new javax.swing.JButton();
        nomeL2 = new javax.swing.JLabel();
        idadeL2 = new javax.swing.JLabel();
        sexoL2 = new javax.swing.JLabel();
        cpfL2 = new javax.swing.JLabel();
        nomeCamp2 = new javax.swing.JTextField();
        idadeCamp2 = new javax.swing.JTextField();
        cpfCamp2 = new javax.swing.JTextField();
        sMasc2 = new javax.swing.JRadioButton();
        sFem2 = new javax.swing.JRadioButton();
        rLabel2 = new javax.swing.JLabel();
        rSim2 = new javax.swing.JRadioButton();
        rNao2 = new javax.swing.JRadioButton();
        sLabel2 = new javax.swing.JLabel();
        cSim2 = new javax.swing.JRadioButton();
        cNao2 = new javax.swing.JRadioButton();
        tLabel2 = new javax.swing.JLabel();
        rCamp2 = new javax.swing.JTextField();
        ajB = new javax.swing.JButton();
        ajB2 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 900));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tab.setPreferredSize(new java.awt.Dimension(200, 200));

        cadP.setBackground(new java.awt.Color(200, 200, 200));

        nomeLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeLabel.setText("Nome Completo");

        idadeLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idadeLabel.setText("Idade");

        cpfLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cpfLabel.setText("CPF");

        sLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sLabel.setText("Sexo");

        sMasc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sMasc.setText("Masculino");
        sMasc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sMascMouseClicked(evt);
            }
        });
        sMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMascActionPerformed(evt);
            }
        });

        sFem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        sFem.setText("Feminino");
        sFem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sFemMouseClicked(evt);
            }
        });
        sFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sFemActionPerformed(evt);
            }
        });

        cLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cLabel.setText("Contágio por COVID-19");

        cSim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cSim.setText("Sim");
        cSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cSimMouseClicked(evt);
            }
        });
        cSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSimActionPerformed(evt);
            }
        });

        cNao.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cNao.setText("Não");
        cNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cNaoMouseClicked(evt);
            }
        });
        cNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNaoActionPerformed(evt);
            }
        });

        rLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rLabel.setText("Grupo de Risco");

        rSim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rSim.setText("Sim");
        rSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSimMouseClicked(evt);
            }
        });
        rSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSimActionPerformed(evt);
            }
        });

        rNao.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rNao.setText("Não");
        rNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rNaoMouseClicked(evt);
            }
        });
        rNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNaoActionPerformed(evt);
            }
        });

        tLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tLabel.setText("Tipo de Risco");

        cadB.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cadB.setText("Cadastrar");
        cadB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout cadPLayout = new javax.swing.GroupLayout(cadP);
        cadP.setLayout(cadPLayout);
        cadPLayout.setHorizontalGroup(
            cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadPLayout.createSequentialGroup()
                        .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cadPLayout.createSequentialGroup()
                                .addComponent(cpfLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cadPLayout.createSequentialGroup()
                                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idadeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)
                                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idadeCamp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))
                    .addGroup(cadPLayout.createSequentialGroup()
                        .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cLabel)
                            .addGroup(cadPLayout.createSequentialGroup()
                                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cSim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(cadPLayout.createSequentialGroup()
                                        .addComponent(sLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rSim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sFem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cNao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rNao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cadPLayout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cadB, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cadPLayout.createSequentialGroup()
                        .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rLabel)
                            .addComponent(tLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        cadPLayout.setVerticalGroup(
            cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadPLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sMasc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sFem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cSim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        tab.addTab("Cadastro", cadP);

        cpfPanel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cpfPanel2.setText("CPF");

        pesqB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pesqB.setText("Pesquisar");
        pesqB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesqBMouseClicked(evt);
            }
        });
        pesqB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqBActionPerformed(evt);
            }
        });

        status.setLayout(new java.awt.BorderLayout());
        status.add(statusL, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cpfPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pesqCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesqB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqB, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
        );

        tab.addTab("Informação", jPanel2);

        cpfLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cpfLabel2.setText("CPF");

        pesqB2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pesqB2.setText("Pesquisar");
        pesqB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesqB2MouseClicked(evt);
            }
        });
        pesqB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesqB2ActionPerformed(evt);
            }
        });

        nomeL2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomeL2.setText("Nome");

        idadeL2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idadeL2.setText("Idade");

        sexoL2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sexoL2.setText("Sexo");

        cpfL2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cpfL2.setText("CPF");

        cpfCamp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfCamp2ActionPerformed(evt);
            }
        });
        cpfCamp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpfCamp2KeyTyped(evt);
            }
        });

        sMasc2.setText("Masculino");
        sMasc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sMasc2MouseClicked(evt);
            }
        });

        sFem2.setText("Feminino");
        sFem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sFem2MouseClicked(evt);
            }
        });

        rLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rLabel2.setText("Grupo de Risco");

        rSim2.setText("Sim");
        rSim2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSim2MouseClicked(evt);
            }
        });
        rSim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSim2ActionPerformed(evt);
            }
        });

        rNao2.setText("Não");
        rNao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rNao2MouseClicked(evt);
            }
        });

        sLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sLabel2.setText("Contágio por COVID-19");

        cSim2.setText("Sim");
        cSim2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cSim2MouseClicked(evt);
            }
        });
        cSim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSim2ActionPerformed(evt);
            }
        });

        cNao2.setText("Não");
        cNao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cNao2MouseClicked(evt);
            }
        });

        tLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tLabel2.setText("Tipo de Risco");

        ajB.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ajB.setText("Ajustar");
        ajB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajBMouseClicked(evt);
            }
        });

        ajB2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ajB2.setText("Excluir");
        ajB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajB2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addComponent(rSim2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(cSim2)))
                        .addGap(221, 221, 221)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNao2)
                            .addComponent(rNao2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cpfLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rLabel2)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(sexoL2)
                                    .addGap(85, 85, 85)
                                    .addComponent(sMasc2)
                                    .addGap(179, 179, 179)
                                    .addComponent(sFem2))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(nomeL2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(idadeL2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idadeCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(pesqCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pesqB2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(cpfL2)
                                            .addGap(18, 18, 18)
                                            .addComponent(cpfCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(rCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(ajB, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ajB2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(sLabel2)
                            .addComponent(tLabel2))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesqB2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeL2)
                    .addComponent(nomeCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idadeL2)
                    .addComponent(idadeCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sexoL2)
                    .addComponent(sMasc2)
                    .addComponent(sFem2))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfL2)
                    .addComponent(cpfCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(rLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSim2)
                    .addComponent(rNao2))
                .addGap(18, 18, 18)
                .addComponent(sLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cSim2)
                    .addComponent(cNao2))
                .addGap(18, 18, 18)
                .addComponent(tLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rCamp2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajB2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        tab.addTab("Ajuste", jPanel3);

        getContentPane().add(tab, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sFemActionPerformed

    private void sMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sMascActionPerformed

    private void cSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSimActionPerformed

    private void cNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNaoActionPerformed

    private void sMascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMascMouseClicked
        sFem.setSelected(false);
    }//GEN-LAST:event_sMascMouseClicked

    private void sFemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sFemMouseClicked
        sMasc.setSelected(false);
    }//GEN-LAST:event_sFemMouseClicked

    private void cSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cSimMouseClicked
        cNao.setSelected(false);
    }//GEN-LAST:event_cSimMouseClicked

    private void cNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cNaoMouseClicked
        cSim.setSelected(false);
    }//GEN-LAST:event_cNaoMouseClicked

    private void rSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSimMouseClicked
        rNao.setSelected(false);
    }//GEN-LAST:event_rSimMouseClicked

    private void rSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSimActionPerformed

    private void rNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rNaoMouseClicked
        rSim.setSelected(false);
    }//GEN-LAST:event_rNaoMouseClicked

    private void rNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNaoActionPerformed

    private void cadBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadBMouseClicked
        boolean d = true;
        if (i > 0) {
            for (int j = 0; j < i; j++) {
                if (cpfCamp.getText().equals(p[j].getCpf())) {
                    d = false;
                    JOptionPane.showMessageDialog(null, "CPF inválido!");
                }
            }
        }
        try {
            ExcessaoEntradaNome.testeNome(nomeCamp.getText());
            ExcessaoEntradaCPF.testeCpf(cpfCamp.getText());
            ExcessaoEntradaIdade.testeId(Integer.parseInt(idadeCamp.getText()));
        } catch (IllegalArgumentException a) {
            JOptionPane.showMessageDialog(null, "Cadastro Formato Incorreto!!!\n" + a);
            d = false;
        } catch (ExcessaoEntradaIdade b) {
            idadeCamp.setText("18");
        }
        if (i > 100) {
            JOptionPane.showMessageDialog(null, "Cadastro Cheio!!!");
            d = false;
        }
        if (d == true) {
            if (rSim.isSelected() == true) {
                if (sMasc.isSelected() == true) {
                    if (cSim.isSelected() == true) {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*aux.replaceFirst(p[exAux].nome, p[]);*/
                                p[exAux] = p[i--];
                                x[exAux] = 1;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new Risco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Masculino", cpfCamp.getText(), tipoCampo.getText(), 1);
                            x[i] = 1;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Masculino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+tipoCampo.getText()+";"+"1"+";"+"\n";
                        }
                    } else {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*ArquivoTxt.substituir(l, exAux);*/
                                p[exAux] = p[i--];
                                x[exAux] = 2;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new Risco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Masculino", cpfCamp.getText(), tipoCampo.getText(), 2);
                            x[i] = 2;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Masculino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+tipoCampo.getText()+";"+"2"+";"+"\n";
                        }
                    }
                } else {
                    if (cSim.isSelected() == true) {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*ArquivoTxt.substituir(l, exAux);*/
                                p[exAux] = p[i--];
                                x[exAux] = 1;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new Risco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Feminino", cpfCamp.getText(), tipoCampo.getText(), 1);
                            x[i] = 1;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Feminino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+tipoCampo.getText()+";"+"1"+";"+"\n";
                        }
                    } else {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*ArquivoTxt.substituir(l, exAux);*/
                                p[exAux] = p[i--];
                                x[exAux] = 2;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new Risco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Feminino", cpfCamp.getText(), tipoCampo.getText(), 2);
                            x[i] = 2;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Feminino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+tipoCampo.getText()+";"+"2"+";"+"\n";
                        }
                    }
                }
            } else if (rNao.isSelected() == true) {
                if (sMasc.isSelected() == true) {
                    if (cSim.isSelected() == true) {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*ArquivoTxt.substituir(l, exAux);*/
                                p[exAux] = p[i--];
                                x[exAux] = 1;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new ForaRisco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Masculino", cpfCamp.getText(), 1);
                            x[i] = 1;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Masculino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+"1"+";"+"\n";
                        }
                    } else {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*ArquivoTxt.substituir(l, exAux);*/
                                p[exAux] = p[i--];
                                x[exAux] = 2;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new ForaRisco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Masculino", cpfCamp.getText(), 2);
                            x[i] = 2;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Masculino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+"2"+";"+"\n";
                        }
                    }
                } else {
                    if (cSim.isSelected() == true) {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*ArquivoTxt.substituir(l, exAux);*/
                                p[exAux] = p[i--];
                                x[exAux] = 1;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new ForaRisco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Feminino", cpfCamp.getText(), 1);
                            x[i] = 1;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Feminino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+"1"+";"+"\n";
                        }
                    } else {
                        if (exAux != -1) {
                            if (i > 1) {
                                /*ArquivoTxt.substituir(l, exAux);*/
                                p[exAux] = p[i--];
                                x[exAux] = 2;
                                exAux = -1;
                                i--;
                            } else {
                                i--;
                            }
                        } else {
                            p[i] = new ForaRisco(nomeCamp.getText(), Integer.parseInt(idadeCamp.getText()), "Feminino", cpfCamp.getText(), 2);
                            x[i] = 1;
                            i++;
                            //aux += nomeCamp.getText()+";"+Integer.parseInt(idadeCamp.getText())+";"+"Feminino"+";"+cpfCamp.getText()+";"+p[i].flag+";"+"2"+";"+"\n";
                        }
                    }
                }
            }
            nomeCamp.setText("");
            idadeCamp.setText("");
            cpfCamp.setText("");
            cNao.setSelected(false);
            cSim.setSelected(false);
            sFem.setSelected(false);
            sMasc.setSelected(false);
            rNao.setSelected(false);
            rSim.setSelected(false);
            tipoCampo.setText("");
        }
    }//GEN-LAST:event_cadBMouseClicked

    private void pesqBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesqBActionPerformed

    private void pesqBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesqBMouseClicked
        int aux = 1;
        for (int j = 0; j < i; j++) {
            if (pesqCamp.getText().equals(p[j].getCpf())) {
                resultLabel.setText(p[j].status());
                aux = 2;
            }
        }
        if (aux == 1) {
            JOptionPane.showMessageDialog(null, "CPF não encontrado");
        }
        pesqCamp.setText("");
    }//GEN-LAST:event_pesqBMouseClicked

    private void pesqB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesqB2MouseClicked
        int aux = 1;
        nomeCamp2.setText("");
        idadeCamp2.setText("");
        cpfCamp2.setText("");
        cNao2.setSelected(false);
        cSim2.setSelected(false);
        sFem2.setSelected(false);
        sMasc2.setSelected(false);
        rNao2.setSelected(false);
        rSim2.setSelected(false);
        rCamp2.setText("");
        for (int j = 0; j < i; j++) {
            if (pesqCamp2.getText().equals(p[j].getCpf())) {
                aux2 = j;
                nomeCamp2.setText(p[j].nome);
                idadeCamp2.setText(Integer.toString(p[j].idade));
                cpfCamp2.setText(p[j].cpf);
                if (p[j].sexo.equals("Masculino")) {
                    sMasc2.setSelected(true);
                } else {
                    sFem2.setSelected(true);
                }
                aux = 2;
                if (x[j] == 1) {
                    cSim2.setSelected(true);
                } else {
                    cNao2.setSelected(true);
                }
                rCamp2.setText(p[j].getTipo());
                if (p[j].getTipo() != null) {
                    rSim2.setSelected(true);
                } else {
                    rNao2.setSelected(true);
                }
            }
        }
        if (aux == 1) {
            JOptionPane.showMessageDialog(null, "CPF não encontrado");
        }
    }//GEN-LAST:event_pesqB2MouseClicked

    private void pesqB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesqB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesqB2ActionPerformed

    private void rSim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSim2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSim2ActionPerformed

    private void cSim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSim2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cSim2ActionPerformed

    private void ajBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajBMouseClicked
        boolean d = true;
        if (i > 0) {
            for (int j = 0; j < i; j++) {
                if (cpfCamp2.getText().equals(p[j].getCpf())) {
                    d = cpfCamp2.getText().equals(p[aux2].cpf);
                }
            }
        }
        try {
            ExcessaoEntradaNome.testeNome(nomeCamp2.getText());
            ExcessaoEntradaCPF.testeCpf(cpfCamp2.getText());
            ExcessaoEntradaIdade.testeId(Integer.parseInt(idadeCamp2.getText()));
        } catch (IllegalArgumentException a) {
            JOptionPane.showMessageDialog(null, a);
            d = false;
        } catch (ExcessaoEntradaIdade b) {
            idadeCamp.setText("18");
        }
        if (d == true) {
            if (rSim2.isSelected() == true) {
                if (sMasc2.isSelected() == true) {
                    if (cSim2.isSelected() == true) {
                        p[aux2] = new Risco(nomeCamp2.getText(), Integer.parseInt(idadeCamp2.getText()), "Masculino", cpfCamp2.getText(), rCamp2.getText(), 1);
                        x[aux2] = 1;
                        i++;
                    } else {
                        p[aux2] = new Risco(nomeCamp.getText(), Integer.parseInt(idadeCamp2.getText()), "Masculino", cpfCamp2.getText(), rCamp2.getText(), 2);
                        x[aux2] = 2;
                        i++;
                    }
                } else {
                    if (cSim2.isSelected() == true) {
                        p[aux2] = new Risco(nomeCamp2.getText(), Integer.parseInt(idadeCamp2.getText()), "Feminino", cpfCamp2.getText(), rCamp2.getText(), 1);
                        x[aux2] = 1;
                        i++;
                    } else {
                        p[aux2] = new Risco(nomeCamp2.getText(), Integer.parseInt(idadeCamp2.getText()), "Feminino", cpfCamp2.getText(), rCamp2.getText(), 2);
                        x[aux2] = 2;
                        i++;
                    }
                }
            } else if (rNao2.isSelected() == true) {
                if (sMasc2.isSelected() == true) {
                    if (cSim2.isSelected() == true) {
                        p[aux2] = new ForaRisco(nomeCamp2.getText(), Integer.parseInt(idadeCamp2.getText()), "Masculino", cpfCamp2.getText(), 1);
                        x[aux2] = 1;
                        i++;
                    } else {
                        p[aux2] = new ForaRisco(nomeCamp.getText(), Integer.parseInt(idadeCamp2.getText()), "Masculino", cpfCamp2.getText(), 2);
                        x[aux2] = 2;
                        i++;
                    }
                } else {
                    if (cSim2.isSelected() == true) {
                        p[aux2] = new ForaRisco(nomeCamp2.getText(), Integer.parseInt(idadeCamp2.getText()), "Feminino", cpfCamp2.getText(), 1);
                        x[aux2] = 1;
                        i++;
                    } else {
                        p[aux2] = new ForaRisco(nomeCamp2.getText(), Integer.parseInt(idadeCamp2.getText()), "Feminino", cpfCamp2.getText(), 2);
                        x[aux2] = 2;
                        i++;
                    }
                }
            }
            nomeCamp2.setText("");
            idadeCamp2.setText("");
            cpfCamp2.setText("");
            cNao2.setSelected(false);
            cSim2.setSelected(false);
            sFem2.setSelected(false);
            sMasc2.setSelected(false);
            rNao2.setSelected(false);
            rSim2.setSelected(false);
            rCamp2.setText("");
        }

    }//GEN-LAST:event_ajBMouseClicked
    private void sMasc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sMasc2MouseClicked
        sFem2.setSelected(false);
    }//GEN-LAST:event_sMasc2MouseClicked

    private void sFem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sFem2MouseClicked
        sMasc2.setSelected(false);
    }//GEN-LAST:event_sFem2MouseClicked

    private void rSim2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSim2MouseClicked
        rNao2.setSelected(false);
    }//GEN-LAST:event_rSim2MouseClicked

    private void rNao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rNao2MouseClicked
        rSim2.setSelected(false);
    }//GEN-LAST:event_rNao2MouseClicked

    private void cSim2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cSim2MouseClicked
        cNao2.setSelected(false);
    }//GEN-LAST:event_cSim2MouseClicked

    private void cNao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cNao2MouseClicked
        cSim2.setSelected(false);
    }//GEN-LAST:event_cNao2MouseClicked

    private void ajB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajB2MouseClicked
        exAux = aux2;
        nomeCamp2.setText("");
        idadeCamp2.setText("");
        cpfCamp2.setText("");
        cNao2.setSelected(false);
        cSim2.setSelected(false);
        sFem2.setSelected(false);
        sMasc2.setSelected(false);
        rNao2.setSelected(false);
        rSim2.setSelected(false);
        rCamp2.setText("");
    }//GEN-LAST:event_ajB2MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        /*ArquivoTxt.gravar(l, aux);*/
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*i = ArquivoTxt.ler(l, p);*/
    }//GEN-LAST:event_formWindowOpened

    private void cpfCamp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCamp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCamp2ActionPerformed

    private void cpfCamp2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfCamp2KeyTyped

    }//GEN-LAST:event_cpfCamp2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajB;
    private javax.swing.JButton ajB2;
    private javax.swing.JLabel cLabel;
    private javax.swing.JRadioButton cNao;
    private javax.swing.JRadioButton cNao2;
    private javax.swing.JRadioButton cSim;
    private javax.swing.JRadioButton cSim2;
    private javax.swing.JButton cadB;
    private javax.swing.JPanel cadP;
    private javax.swing.JTextField cpfCamp;
    private javax.swing.JTextField cpfCamp2;
    private javax.swing.JLabel cpfL2;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel cpfLabel2;
    private javax.swing.JLabel cpfPanel2;
    private javax.swing.JTextField idadeCamp;
    private javax.swing.JTextField idadeCamp2;
    private javax.swing.JLabel idadeL2;
    private javax.swing.JLabel idadeLabel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeCamp;
    private javax.swing.JTextField nomeCamp2;
    private javax.swing.JLabel nomeL2;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JButton pesqB;
    private javax.swing.JButton pesqB2;
    private javax.swing.JTextField pesqCamp;
    private javax.swing.JTextField pesqCamp2;
    private javax.swing.JTextField rCamp2;
    private javax.swing.JLabel rLabel;
    private javax.swing.JLabel rLabel2;
    private javax.swing.JRadioButton rNao;
    private javax.swing.JRadioButton rNao2;
    private javax.swing.JRadioButton rSim;
    private javax.swing.JRadioButton rSim2;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JRadioButton sFem;
    private javax.swing.JRadioButton sFem2;
    private javax.swing.JLabel sLabel;
    private javax.swing.JLabel sLabel2;
    private javax.swing.JRadioButton sMasc;
    private javax.swing.JRadioButton sMasc2;
    private javax.swing.JLabel sexoL2;
    private javax.swing.JPanel status;
    private javax.swing.JLabel statusL;
    private javax.swing.JLabel tLabel;
    private javax.swing.JLabel tLabel2;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField tipoCampo;
    // End of variables declaration//GEN-END:variables
}
